<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<html lang="en">
	<title>My Profile</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<header>
	<div class="main">
	<ul>
	
	<li><a href="#">Home</a></li>
	<li><a href="#">Service</a></li>
	<li><a href="#">Gallery</a></li>
	<li><a href="#">About</a></li>
	<li><a href="#">Contact</a></li>

</ul>
</div>
<div class="title">
	<h1><u>My Project</u></h1>
	
</div>
<div class="image">
<img src="2.jpg" style="width:auto;">
</div>
</header>
</body>
</html>
